### PR TITLE
Glide airspeed control fix

### PR DESCRIPTION
**Pull request by KeesGuijt**
if one or more of these setting are used, compilation errors may occur, and/or code will not function;

GAINS_VARIABLE                      1
ALTITUDE_GAINS_VARIABLE             1
GLIDE_AIRSPEED_CONTROL  1

fixing this may help to fix SPEED_CONTROL as well.

Best regards,
Kees

### CODE REVIEW

**Comment by phollands** [comment]
Thanks Kees. 
Robert do you have an pertinent comments about these commits, before I do some testing myself. Best wishes, Pete

**Comment by phollands** [comment]
Kees, given the nice weather in the Netherlands, have you by any chance already flown this fix ? Best wishes, Pete

**Comment by KeesGuijt** [comment]
Yes, for 86 minutes!

Kees 

Sent from my Cyanogen phone

On May 7, 2016 11:06 PM, Pete Hollands <notifications@github.com> wrote:

Kees, given the nice weather in the Netherlands, have you by any chance already flown this fix ? Best wishes, Pete

**Comment by phollands** [comment]
OK. Great. Well if Robert is happy, then we'll merge this.

The changes look more complex at first than are necessary, because of the
merged changes from master. I have now become adept at  keeping my various
branches up to date from upstream master using rebase. It only takes a
moment, and then all the local changes come after the changes in master.
That would make this type of Pull Request look a lot simpler. Although it
pretty easy to see what is a merge from Master, and what is new.

Best wishes, Pete

**Comment by KeesGuijt** [comment]
Pete,

You're right. I did some cleaning.

Best regards,
Kees

**Comment by phollands** [comment]
Nice.  I like it.

I'll ping Robert to make sure he's seen this pull request. Github may not have been included automatically by email.

Best wishes, Pete

**Comment by Inspirati** [comment]
I'd prefer to see the code changes and the project file updates in separate PR's

**Comment by Inspirati** [comment]
Oh, sorry, I see this has now been done. The change to remove AH_THROTTLE_ONLY from the conditional looks suspicious, however I'm not very familiar with this functionality and am not currently in a position to do any such testing. IIRC, that code has existed for quite some time, but if you're sure it's the way to go, I am good to see it merged.

**Comment by phollands** [comment]
Robert,  Thanks for pointing out the THROTTLE_ONLY change. This is the only place in all the code in Master where the macro THROTTLE_ONLY is used in all of the code. It is never defined. So it is redundant. Best wishes, Pete

**Pull request merged**
