### PR TITLE
Create consistent naming of flightplans and options files in the Config Directory

### PR DESCRIPTION
**Pull request by phollands**
This is my first pass on a pull request, partly because I want to see whether it upsets the Travis build system.  MatrixPilot, RollPitchYaw and LedTest all build correctly with MPLAB-X.

screen shot 2016-09-20 at 18 20 24

I have not updated any of the MPLAB IDE projects.  Any volunteers want to work with me on that ? Or are we ready to deprecate MPLAB IDE and just use MPLAB-X. I think the time has come.

VIsual Studio for MatrixPilot-SIL under Windows. Robert would you be able to look at that ? I have done some editing of the XML files (vcxproj) , but I have not been a user of Visual Studio.

matrixpilot in MatrixPilot-SIL for Unix is building with Makefile.unix under MacOs. 

matrixpilot for MatrixPilot_SIL using Makefile.Win:- I have edited changes into the file but have not been able to test it. Any Vounteers ?

silcat is not building.  I've not been able to find out why. It jwill not link under MacOs between SILCat.o and UDBSocketUnix.o. This issue existed prior to this set of commits. 

I am not going to change the order of the commits, or squash them down, as it is tedious to deal with conflicts in the configuration.xml files. I do not want to hand edit the xml normally produced by MPLAB-X. These commits will all be merged under this one Pull Request.

I will want to do some more testing tomorrow.

### CODE REVIEW

**Comment by phollands** [comment]
Kees, I've decided to split out the gains_variables.h file after this Pull Request. That way this Pull Request is just about renaming the files.

**Comment by elgarbe** [comment]
> I have not updated any of the MPLAB IDE projects. Any volunteers want to work with me on that ? Or are we ready to deprecate MPLAB IDE and just use MPLAB-X. I think the time has come

I would like to learn and help on anything you consider that I could do.
Unfortunately my dsPIC knowledge is very limited.
If you think that I can learn something that could be usefull for the development process I could give  a try.

BW

**Comment by phollands** [comment]
Leo,  Thanks for the offer. Your most valuable help would be to test fly
"master" with your plane, and publish the configuration and logs that
result. With regard to configurin up MPLAB IDE, I'm hoping that some of the
other core developers will have some time or that they will agree that the
time has come to move to just using MPLAB-X.  Best wishes, Pete

**Comment by KeesGuijt** [comment]
Pete,

was  Tools/flight_analyzer/flan_config added intentionally?

Kees

**Comment by phollands** [comment]
Thanks for pointing that out. No,  I did not mean to add flan _config. I
will take it out.

**Comment by KeesGuijt** [comment]
You're welcome. 92 is a lot....

Kees

**Pull request merged**
