### PR TITLE
Fix barometer pressure

### PR DESCRIPTION
**Pull request by phollands**
This is a fix for issue #124 .

### CODE REVIEW

**Comment by phollands** [comment]
Flight Test on UDB5 went OK.  The GPS Altitude Track and Dead Reckoning Track (from barometer) are close to each other in normal flight and climbs. The screenshot below shows both the IMU Track and the GPS track together.

 Pressure value in SERIAL_UDB_EXTRA shown as:- 
:**tmp208:prs101502:alt0**:bmv0:mA10:mAh3:DH0: which is correct for my location and height at origin.

screen shot 2017-02-18 at 17 07 50

So if there are no further comments suggesting changes, I shall merge this in tomorrow.

**Comment by phollands** [comment]
Ground Tested the AUAV3 with barometer. Tests OK. 
(slightly higher temperature, but tested inside, and is situated on main AUV3 board.)
**tmp262:prs101381**:alt0:

Best wishes, Pete

**Comment by elgarbe** [comment]
Peter, do you plan to merge the code today? I'm preparing a mission today (I want to test my 1.2GHz biquad antenna) and could hook up my barometer to try it.
best wishes!

**Comment by phollands** [comment]
Hi Leo,

Your email crossed as I merged the code at the same time. All done.

Best wishes, Pete

**Comment by phollands** [comment]
One thing that I have been thinking about. Does the barometer code work
with the magnetometer code at the same time on the same I2C interface ? As
I am one of the few people that use the magnetometer successfully, I
suspect that this currently is only an issue for myself. I will get to
testing that soon.

Best wishes, Pete

**Comment by elgarbe** [comment]
I have one of this: http://selfbuilt.net/shop/gy-80-inertial-management-unit
so in any time I could test magnetometer as well. But I'm concern about calibration, I think that I read about the difficult to calibrate this sensor.

**Comment by Inspirati** [comment]
the mag and baro 'should' work on the same bus together - albeit it's been
a long time since i wrote that code, and it was around the same time as i
wrote the baro code which it seems you've just found to be in error, so you
mileage will no doubt vary. for memory, the code which handles the two
devices together is somewhat convoluted as they work at different sampling
rates, and one requires several more transactions to get a result than the
other. thus i suspect it may all look somewhat confusing (at least at first)

**Comment by phollands** [comment]
Thanks Rob, I'll take a look before I fly.

**Comment by phollands** [comment]
Leo, Yes, I have **not** yet been successful with the HMC5883L, but I do have success with the older HMC5843 chip.  The offsets on the HMC5883L that I have in my possession  are much larger than the 5843, and I think that Bill's automatic calibration of offsets for the 5883L is too slow. I looked into it a couple of years ago, and made some tools for visualising the offsets in 3D (using Python). It could be fixed if we were motivated to do that (i.e. there was a good reason. e.g. flying without GPS).

Hope you have managed to get a good flight in.

Best wishes, Pete

**Comment by elgarbe** [comment]
I have a really good flight today. I will post it later. 10km away and back. Barometer seems to work excelent.

**Comment by phollands** [comment]
Leo, That is good news. Look forward to seeing your post on uavdevboard.

**Pull request merged**
