### PR TITLE
Whitespace and newline consistency commit

### PR DESCRIPTION
**Pull request by Inspirati**

### CODE REVIEW

**Comment by phollands** [comment]
Robert,  Thanks for all the Travis configuration work.

On whitespace enforcement,  I would like to help. Can you point me to the guidelines  you are using and any example configuration files you may have. I am using MPLAB-X.

I have read the commits and am happy with the  pull request myself. 

I am away at the moment and travelling.

Best wishes,  Pete

**Comment by magicrub** [comment]
I see 42 commits on 6 files including a few merges and reverts.  Please squash for clarity.

**Comment by Inspirati** [comment]
superceded

**Comment by magicrub** [comment]
Great example of where you could do an intetactive re base and fold it into one-ish commit. Then force push to the same branch and simplify the same pull request.

**Comment by Inspirati** [comment]
Ha!, unfortunately I couldn't get that to work for me, so I deleted my fork
and started from scratch )-:

**Comment by magicrub** [comment]
Were you using source tree?

**Comment by Inspirati** [comment]
no, command line only. i suspect there may have been a few reasons behind
why git was presenting me with its rather cryptic error messages. firstly,
i was not working in a branch )-:

**Pull request closed without merging**
