### PR TITLE
Reduce CPU Loading by revision of A/D for UDB5. 

### PR DESCRIPTION
**Pull request by wjpremerlani**
use Mark Whitehorn's timing constants to reduce CPU loading.

### CODE REVIEW

**Comment by MatrixPilot** [comment]
hey William, log into skype

**Comment by phollands** [comment]
I am going to enclose Bill's comments on this PR which he has sent to me ....

Peter,

It turns out that Mark Whitehorn had already revised the sampling rate for the UDB5 A/D. However, his revisions were turned off. All I had to do was to turn them on.

The sampling rate is still a bit higher than it needs to be, but it is good enough, so in the interest of efficiency, lets go with Mark's values for now, we can always fine tune later.

Here are the CPU loading numbers:

legacy sampling rate, CPU loading at 24%
Mark's sampling rate at 16 MIPs, CPU loading at 13%
Mark's sampling rate at 32 MIPs, CPU loading at 6%.

At Mark's sampling rates, noise level is low and bandwidth is high. So, its a good engineering compromise between performance and CPU load.

Best regards,
Bill

**Comment by MatrixPilot** [comment]
howdy guys, for memory this seems about right with me too. Marks
engineering of our equations is as sound as we might otherwise get.

**Comment by phollands** [comment]
Thanks to Leo, in Argentina, who has kindly done a test flight (LOG0079,TXT)  of master to re-confirm that this change (reducing the A/D measurement rate on the UDB5) works fine for the calculation of battery voltage, amperage, and total current used.  The flight went smoothly. The CPU usage was reduced from 32% to 22% for his setup which uses On Screen Dispaly (OSD). I have reviewed the logs and all looks fine.

**Pull request merged**
