### PR TITLE
RSSI signal, in OSD, will blink when the signal strenght drops below a configurable value

### PR DESCRIPTION
**Pull request by elgarbe**
Just a blinking alarm on low RSSI in the native OSD
[Video for the new feature](https://youtu.be/rVJ379R7bZ0)

### CODE REVIEW

**Comment by chiloschista** [comment]
Hello,
I would like to have those blinking warnings selectable.
I'm not a fan of blinkers, they are distracting, I prefer keep them 
under control myself.
RSSI can jump a lot, especially with certain systems. It would then 
start and stop blinking all the time.
Not sure that 10% is a good value also, it depends where a user set his 
usable range. On several planes I did set the no trepassing level at 0%, 
knowing at 0% I still had control. It is not an absolute value.
Same could be sayd about satellites number.
Ric

Il 16.11.2016 13:55, elgarbe ha scritto:

**Comment by elgarbe** [comment]
Ok, no problem. I will add conditional compilation and treshold configuration.
Is the word FLASH well used here? do I have to use blink instead?

Leo

**Comment by phollands** [comment]
Flash or blink is fine for me.

**Comment by elgarbe** [comment]
I rebase this branch onto new master and solve a conflict.
Now it is ok to merge.
Thank

**Comment by phollands** [comment]
Ric, Thanks for your comments. Leo has made GPS snd RSSI "low value flashing" an optional feature. Merging. Best wishes, Pete

**Pull request merged**
