### PR TITLE
Uncomment the MAVLINK_BAUD macro and assign 57600, as the MAVLink def…

### PR DESCRIPTION
**Pull request by KeesGuijt**
…ault serial speed, Setup MAVLink initialisation. This change may be incomplete.

### CODE REVIEW

**Comment by KeesGuijt** [comment]
Hi,
i found one issue so far:
 the six supplied files in \Matrixpilot folder will not compile:
		build\UDB5\parameter_table.o(.const+0x2de):E:\gentlenav.latest.trunk.svn -mavtest\MatrixPilot\..\MatrixPilot\parameter_table.c: undefined reference to `dcm_declination_angle'
		Link step failed.
  this can be fixed by adding mag_drift.c to the sourcefiles in libDCM

and we'll have to adress two issues:
 
- describe how to enable mavlink and warn in options.h and wikis  (not allowing SERIAL_OUTPUT_FORMAT == SERIAL_MAVLINK)
- do a config check in  config_tests.c (not allowing SERIAL_OUTPUT_FORMAT  SERIAL_MAVLINK)


- we could fix mavlink, and leave the AUX port alone for now
or
- we could fix mavlink, and map the selected SERIAL_OUTPUT_FORMAT to AUX when USE_MAVLINK == 1

in that case, 
- add AUX
- map the selected SERIAL_OUTPUT_FORMAT to AUX when USE_MAVLINK == 1
- add extra explanations to options.h and wikis

Best wishes,
Kees

**Comment by phollands** [comment]
Kees, I hope Robert may comment on some of this stuff. After I have done the next flight analyzer improvement, I am going to start trying to compile and test MAVlink in earnest. Originally MAVLINK was deliberately an exclusive option against say SERIAL_UDB_EXTRA. I never wanted to run both together. This is because, in my view, SERIAL_UDB_EXTRA is largely a legacy and deprecated protocol. For a year or two, I ensured that MAVLINK had all of the SERIAL_UDB_EXTRA (SUE) fields and functionality. In fact the fields and logic in MAVLink were deliberately a perfect copy of SERIAL_UDB_EXTRA. Flight Analyzer, would reproduce a traditional SUE LOG000123.TXT file from a MatrixPilot MAVLink binary file, to allow people to have time to make the transition to using purely mavlink tools. The other part of MAVLink that we had was a) The ability to specify which parameters could be changed dynamically in flight b) The ability to store parameters in the on board storage c) The ability to specify what was done with on board storage parameters on a hot reboot or a cold power on boot. So there is a lot to review, and a lot to discuss with Robert, yourself and others. Initially I just want to see the basic MAVLink protocol running from plane to ground control stations (QGroundControl, MAVProxy for now).

**Comment by KeesGuijt** [comment]
Peter,

Having two serial ports with telemetry can have advantages, like adding FrSky telemetry support (no Teensy needed!). It can also be useful as a debugging tool, while testing with mavlink. 
But for now, i think i have a practical solution. 

If there is consensus, we could simply rename all occurences of  "USE_MAVLINK == 1"  back to  "SERIAL_OUTPUT_FORMAT == SERIAL_MAVLINK"
and keep defining Mavlink in the usual way.

This would also solve another thing i discovered: there is also references to SERIAL_MAVLINK  in example options.h files, config_tests.c, defines.h, nv_memory_options.h, 32 files in all.
 
Hope to hear how the other developers feel about this.

Kees

**Comment by phollands** [comment]
Actually I am personally happy with your suggestion to change the #if defines. My focus is on getting trunk to flyable state. Then, if we are in agreement, we can continue to with Robert, in his direction, using new feature branches to merge back into Master. But right now, my goal is to get Master back into a good well tested state most of the old functionality working. So I am happy to go with your solution. Robert, are you OK with that ?

**Comment by Inspirati** [comment]
I'm okay with anything you feel needs to be done in order to have master working in a state that you believe is best for now. However I've always felt pretty strongly about 'rolling back' any 'advances', and that said, would encourage the development of solutions to the configuration options to allow the features to coexist. For among other several other reasons, all the points Kee's has pointed out in his first paragraph above - there was a certain level of method to my madness in originally moving forwards on this motivation. If existing development is rolled back, I do expect such features to remain relegated into feature branches which over time tend towards for of a fork, which never keeps up with ongoing master development directions. This was probably my main motivation for trying in earnest to get as many development features into trunk/master as soon as possible in the first place. In past years I saw too many developments which were being contributed by other key contributors, which quite quickly became so divergent from advances in master, that they simply became to tedious to 'keep in sync' - and have since, sadly, become lost in the branch noise.

I am a believer in adopting a philosophy that any optional features in master may not work properly, and more-so that they just shouldn't present any standard configuration flight hazards when not enabled. Along those lines, I think supporting more stable 'release' branches for use by new adoptees of our flight stack, could be a better solution.

Also, I suspect there may be more to it than simply changing "USE_MAVLINK == 1" back to "SERIAL_OUTPUT_FORMAT == SERIAL_MAVLINK", however I could easily be mistaken here..

Please keep in mind, another of my intentions, given we have the code space, was to have as much of the codebase as possilbe, built in a single default build - if only to catch build time conflicts without having to manage many optional build time configurations. When I was working with so many options, for so many targets, the exponential growth in overheads became prohibitive to keep up with testing.

However today, travis could help a lot with that issue.

**Comment by KeesGuijt** [comment]
Hi, 

Sorry about the revert and the typo's. But this may be the solution to fix Mavlink quickly. 

Is there a way to update projectfiles in the MatrixPilot folder without opening them? The build tool only generates xxx.Config files?
6 projectfiles need the libDCM\mag_drift.c added to sourcefiles.

Cheers,
Kees

**Comment by phollands** [comment]
Hi Kess,

so you did you try proj_gen.bat (Windows).
<https://github.com/MatrixPilot/MatrixPilot/blob/master/proj_gen.bat> I see
that has more different types of projects than the Unix / Mac version
(proj_gen.sh) ?
I have not used them much myself, but tend to work off the received
projects from Master.

Best wishes, Pete

**Comment by KeesGuijt** [comment]
Pete, 
I did, but i want to replace the project files in the MP folder, that are not named xxx.Config. renaming them after creation seems wrong to me.

Thanks,
Kees

Sent from my Cyanogen phone

On Apr 25, 2016 9:05 PM, Pete Hollands <notifications@github.com> wrote:

Hi Kess,

so you did you try proj_gen.bat (Windows).
<https://github.com/MatrixPilot/MatrixPilot/blob/master/proj_gen.bat> I see
that has more different types of projects than the Unix / Mac version
(proj_gen.sh) ?
I have not used them much myself, but tend to work off the received
projects from Master.

Best wishes, Pete

**Comment by Inspirati** [comment]
you could add a couple of commands to the proj_gen script to rename them,
and then they would be named however you prefer 'upon creation'!

the state of the proj_gen scripts are typically in quite a state of flux,
as I used to fiddle with them to suit whatever builds i was targeting at
any given time.

a lot of the lines are intended to be there as examples of what optional
commands can be given.

post any questions you have about them and i'll do my best to clarify.

**Comment by KeesGuijt** [comment]
Hi,

using proj_gen from the tools folder, i got files like:

     MatrixPilot-UDB4-Config.mcp

i modified pyProjectCreator.py like this: 

+#	prjname = opts.name + "-" + opts.target + "-" + opts.config[0].replace("/", " ").split(" ")[-1]
+	prjname = opts.name + "-" + opts.target

i now got files like:

     MatrixPilot-UDB4.mcp

when compared to the orginal files there are some differences:

@@ -9 +9 @@ dir_bin=
-dir_tmp=build/UDB4
+dir_tmp=MatrixPilot-UDB4.C30/build

@@ -1687 +1687 @@ format=0
-Pre-Build=cscript "..\libUDB\fixDeps.vbs" "../Config\options.h" "..\libUDB\fixDeps.h"
+Pre-Build=cscript "..\libUDB\fixDeps.vbs" "../Config" "..\libUDB\fixDeps.h"

could this be important?

Kees

**Comment by Inspirati** [comment]
Hi Kees,

The .mcp files are project for MPLAB-8, which other than Bill and myself, I
don't know that anybody would be using them.

FixDeps is kinda optional anyhow, but the difference seems to match the new
setup with options files being in the ./Config directory, which is a good
thing.

As for the dir_tmp, well I'd expect it's just that, a path to a directory
for build temporary files, so again, shouldn't matter much.

If you do find a need to change/fix any of these, you'll find they come
from the template file(s) at ./Tools/Build/mplab8-template.txt

A bit of history; I got fed up with trying to maintain all the various
project files as traditionally shipped with the MatrixPilot directory,
however never removed them from trunk as I never consulted others about
such - but did stop keeping them current.

For a long time now I've always used the project generator, and simply open
whichever project I'm interested in working on directly in the ./build
directory. I'd encourage others to start doing the same.

**Comment by KeesGuijt** [comment]
Robert, Pete,
Thanks for your answers.
I wanted to bother with maintaining all the various
project files as traditionally shipped with the MatrixPilot directory only one more time...
I'm already using the projects from the _build folder myself.

I think the mavlink fix is now ready and tested. I tried to do a rebase to clean it up a bit, but with little succes. I could do a pull request from my branch Mavlink_init2. I hope we all agree on this fix now?

All the best,
Kees

**Comment by phollands** [comment]
Kees,

Thanks very much.

Can you provide some more details on the tests that you did. I will do some
as well over the next few days.

The Pull Request Merge button provides me with the option to squash all
your commits into one, so that will then keep the history tidy. I can do
that, if you like once, we agree to go ahead.

If you think Mavlink_init2 is cleaner and better, then yes, let's do a pull
request on that branch. I'll then just close this currenet pull request
without a merge, and work on the next one.

Best wishes, Pete

**Comment by KeesGuijt** [comment]
Pete,

I tested some random combinations of the following;
- board type
- Mplab project file version (8 or.X)
- project location (_build or /MatrixPilot)
- telemetry types SERIAL_NONE,SERIAL_MAVLINK, SERIAL_XXX ...
- SERIAL_BAUDRATE 'ndef', or any valid value
I monitored the output to verify the correct output and baudrate. With Mavlink i checked to see if the onboard parameters where transmitted ok.
This was to verify if the old definitions will be converted to the new correctly (while keeping it intact). 
Once the proper code is selected, i assume the serial code is correct.
I have choosen not to test the new telemetry selection method, this is for later.

I'm ok with using this pull request, the changes end up identical. I would like two commits if possible; one for the fix, and one for the projectfiles.

Good luck with your testing.

Thanks,
Kees

**Comment by phollands** [comment]
Kees,

To make two commits, that will require an interactive rebase.  Rebases are
usually done on private branches on a PC that have not been pushed to
origin. If it has gone to origin, the you would have to do a force push, to
re-write the history of your branch on your repository of github, after
you've done the rebase. I think the Pull request system could cope with
that;  but I'm not sure yet.

According to Tom Pittenger, he uses interactive rebasing all the time, and
loves it. He gave me a live demo. So I'll do some experimentation (and
possibly a follow on video) and get back to you.

Once the refined commits (two commits) are in place, only then will I do
the testing.

I will test the functionality of MAVLink in terms of Head Up Display in
QGroundControl, and parameter changing. Robert, if you expect waypoint
lists to work, and be presented on a map, then please let me know. I will
also test out Mavproxy. (I find being able to tune parameters while the
plane is flying is hugely useful).

Best wishes, Pete

**Comment by magicrub** [comment]
handy command for force pushing current branch without having to type in
the branch name:

git push origin HEAD -f

**Comment by magicrub** [comment]
and yes, if you force push to a branch that is currently a pending pull
request then github magically realizes this and updates the PR and re-runs
CI if configured.

**Comment by KeesGuijt** [comment]
Hi Tom, Pete,

git push origin HEAD -f done.
(using Terminal)

Thanks.
Kees

**Comment by magicrub** [comment]
the force push is only needed if you change your history via rebase
interactive or some other special actions. You should only use the -f if a
normal push fails.

**Comment by phollands** [comment]
Kees,

Thanks for the revised commit history. Glad you now have interactive rebase
working. I've pulled mavlink_init branch directly from your repo to mine,
for testing purposes. Initial compile is OK.  Hope to get on with more
testing tomorrow.

Best wishes, Pete

**Comment by phollands** [comment]
Hi Kees, 
Compiles OK for UDB4, UDB5, AUAV3 under MPLAB-X.
Head Up Display in QGroundControl v2.7.1 (old now), working correctly on Windows 7.
Real Time Graphs working correctly.
Parameter Editor is not working in that verison of QGroundControl, but it may not be an issue with our code; will need looking into separately from this Pull Request.

If I forget to set baud rate in options.h I get a lot of messages from the #pragma warning in mavlink_options.h every time that files is included in another file. So a lot of messages on the screen. I wonder if that would be better just warning once, by including the warning in the MAVLink.c code rather then the mavlink_options.h include file ? I wonder what you think on that.
screen shot 2016-04-27 at 21 29 17
screen shot 2016-04-27 at 21 32 31

I am fairly happy with this Pull Request. Just the pragma statement to discuss.

Best wishes, Pete

**Comment by KeesGuijt** [comment]
Peter,

Nicely spotted.
I’ve committed a modified version.

Kees

**Comment by phollands** [comment]
Kees,

I think the pragma message has to be in quotes or it is "ignored" by the
compiler.
#pragma "warning SERIAL_BAUDRATE set to default value of 57600 bps"

Without quotes:-
[image: Inline images 1]

With quotes:-
[image: Inline images 2]

The second compile has output the full details about using 57600 bps.

I would pop the quotes in in myself, but the Pull Request system puts you
in the driving seat, and does not let me make the change,
as it is based on your commit from your repo.

Hope to do a flight test today, and then merge  this pull request.

Best wishes, Pete

**Comment by phollands** [comment]
Kees, 

I did the following tests today and I'm ready to merge this in, once the commit has quotes on the pragma message.

I tested MAVLink on the UDB4 in HILSSIM with Tridge's mavproxy. Its receiving all the data. Status is wrong (but I did not specify to use the matrixpilot dialects yet so I was using ardupilot dialect). e.g. Manual mode says CIRCLE. I was able to use the mavproxy param editor to change PID values in the board while it was operational. So that functionality from a couple of years ago is working. There is a bunch of work to improve the number of features that we support, but the basic communication protocol is working.

I also tested the ability to store mavlink data direct to OpenLog and process it with flan.pyw. I did this on a ground test of the autopilot stack for UDB4, UDB5, AUAV3. Flan.pyw correctly detects that the LOG.TXT file is binary and changes it to LOG.RAW.  It does then attempt to  produce an ascii text SUE compatible file; but it is out of date for Helical Turns, and the F2: format line is split incorrectly  into two lines. All that will need fixing up in future work and is not relevant to this Pull Request.  

So once the quotes issue on the pragma test is done; and optionally (your call) a rebase to squash the commits back to two main commits, then I would like to press the "Merge Pull Request" button.

Best wishes, Pete

**Comment by KeesGuijt** [comment]
Pete,

I looked for examples in the rest of the code. Removing pragma works even nicer. Go ahead with the pull if you like (if you like the message output now). 

All the best,
Kees

**Comment by KeesGuijt** [comment]
Pete,
Great.

Thanks,
Kees

**Comment by phollands** [comment]
Thank you for your ideas and contributions. I think your glider project is
super and I also think you are the Master of Logo.

Best wishes, Pete

**Comment by Inspirati** [comment]
Beware, those (#pragma) warning statements are a real pain in the #### when
it comes to compiler portability. That's the purpose of the pragma. IIRC,
without the annoyingness of the pragma, just the 'warn' statement leads to
later failure with some of the other compilers we otherwise 'support'.

**Pull request merged**
