### PR TITLE
SILSIM fix and HILSIM X-Plane64

### PR DESCRIPTION
**Pull request by Inspirati**
Fix SILSIM and add a 64-bit build of the XPlane plugin for linux.

(the fix for SILSIM is in libDCM.c)

### CODE REVIEW

**Comment by phollands** [comment]
Rob,
I am trying to test this all out properly. Bear with me while I get a Windows 10 environment together. In the meantime, I've built your branch under Ubuntu 16.04. It builds OK. However there are two warnings, which it would be nice to remove, so that we get a completely clean build.

```
../../MatrixPilot/telemetry_log.c: In function ‘log_write’:
../../MatrixPilot/telemetry_log.c:198:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare] 
```
And also:-
In file included from SILcat.cpp:20:0:
```
SILcat.cpp: In function ‘int main(int, char**)’:
SIL-config.h:34:45: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
 #define SILSIM_TELEMETRY_HOST               "127.0.0.1"
                                             ^
SILcat.cpp:51:18: note: in expansion of macro ‘SILSIM_TELEMETRY_HOST’
  char *udpHost = SILSIM_TELEMETRY_HOST;

```

**Comment by phollands** [comment]
For the HILSIM build, using the branch of this PR,  I initially had a failure on Ubuntu 16.04 as follows:-

```
hollands@ubuntu:~/MatrixPilot/Tools/HILSIM_XPlane$ uname -a
Linux ubuntu 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
phollands@ubuntu:~/MatrixPilot/Tools/HILSIM_XPlane$ make clean
Cleaning out everything.
rm -rf ./build
phollands@ubuntu:~/MatrixPilot/Tools/HILSIM_XPlane$ make
mkdir -p build/obj32/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m32 -c HILSIM.cpp -o build/obj32/HILSIM.o
In file included from /usr/include/inttypes.h:25:0,
                 from /usr/include/GL/glext.h:1420,
                 from /usr/include/GL/gl.h:2055,
                 from stdafx.h:19,
                 from HILSIM.cpp:1:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
Makefile.unix:78: recipe for target 'build/obj32/HILSIM.o' failed
make: *** [build/obj32/HILSIM.o] Error 1
phollands@ubuntu:~/MatrixPilot/Tools/HILSIM_XPlane$
```

Looking up on the Internet, I did the following install:-

`phollands@ubuntu:/usr/src$  sudo apt-get install g++-multilib`

And then the build went ahead without a problem.

```
phollands@ubuntu:~/MatrixPilot$ cd Tools/HILSIM_XPlane/
phollands@ubuntu:~/MatrixPilot/Tools/HILSIM_XPlane$ make clean
Cleaning out everything.
rm -rf ./build
phollands@ubuntu:~/MatrixPilot/Tools/HILSIM_XPlane$ make
mkdir -p build/obj32/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m32 -c HILSIM.cpp -o build/obj32/HILSIM.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj32/HILSIM.o -o build/obj32/HILSIM.cppdep HILSIM.cpp
mkdir -p build/obj32/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m32 -c SerialIO.cpp -o build/obj32/SerialIO.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj32/SerialIO.o -o build/obj32/SerialIO.cppdep SerialIO.cpp
mkdir -p build/obj32/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m32 -c Setup.cpp -o build/obj32/Setup.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj32/Setup.o -o build/obj32/Setup.cppdep Setup.cpp
mkdir -p build/obj32/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m32 -c UDBSocketUnix.c -o build/obj32/UDBSocketUnix.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj32/UDBSocketUnix.o -o build/obj32/UDBSocketUnix.cdep UDBSocketUnix.c
mkdir -p build/obj32/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m32 -c stdafx.cpp -o build/obj32/stdafx.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj32/stdafx.o -o build/obj32/stdafx.cppdep stdafx.cpp
mkdir -p build/obj32/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m32 -c utility.cpp -o build/obj32/utility.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj32/utility.o -o build/obj32/utility.cppdep utility.cpp
Linking build/HILSIM-linux/32/HILSIM-linux32.xpl
mkdir -p build/HILSIM-linux/32/
gcc -m32 -static-libgcc -shared -Wl,--version-script=exports.txt -o build/HILSIM-linux/32/HILSIM-linux32.xpl ./build/obj32/HILSIM.o ./build/obj32/SerialIO.o ./build/obj32/Setup.o ./build/obj32/UDBSocketUnix.o ./build/obj32/stdafx.o ./build/obj32/utility.o 
mkdir -p build/obj64/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m64 -c HILSIM.cpp -o build/obj64/HILSIM.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj64/HILSIM.o -o build/obj64/HILSIM.cppdep HILSIM.cpp
mkdir -p build/obj64/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m64 -c SerialIO.cpp -o build/obj64/SerialIO.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj64/SerialIO.o -o build/obj64/SerialIO.cppdep SerialIO.cpp
mkdir -p build/obj64/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m64 -c Setup.cpp -o build/obj64/Setup.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj64/Setup.o -o build/obj64/Setup.cppdep Setup.cpp
mkdir -p build/obj64/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m64 -c UDBSocketUnix.c -o build/obj64/UDBSocketUnix.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj64/UDBSocketUnix.o -o build/obj64/UDBSocketUnix.cdep UDBSocketUnix.c
mkdir -p build/obj64/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m64 -c stdafx.cpp -o build/obj64/stdafx.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj64/stdafx.o -o build/obj64/stdafx.cppdep stdafx.cpp
mkdir -p build/obj64/
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -m64 -c utility.cpp -o build/obj64/utility.o
g++ -DXPLM200=1 -DXPLM210=1 -DAPL=0 -DIBM=0 -DLIN=1 -DNIX=1 -I./include -fPIC -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-variable -MM -MT build/obj64/utility.o -o build/obj64/utility.cppdep utility.cpp
Linking build/HILSIM-linux/64/HILSIM-linux64.xpl
mkdir -p build/HILSIM-linux/64/
gcc -m64 -static-libgcc -shared -Wl,--version-script=exports.txt -o build/HILSIM-linux/64/HILSIM-linux64.xpl ./build/obj64/HILSIM.o ./build/obj64/SerialIO.o ./build/obj64/Setup.o ./build/obj64/UDBSocketUnix.o ./build/obj64/stdafx.o ./build/obj64/utility.o 
nm -D ./build/HILSIM-linux/64/HILSIM-linux64.xpl | grep "T "
000000000000eaf4 T _fini
0000000000002908 T _init
000000000000363c T XPluginDisable
00000000000036b3 T XPluginEnable
0000000000003848 T XPluginReceiveMessage
0000000000003160 T XPluginStart
00000000000035ff T XPluginStop
phollands@ubuntu:~/MatrixPilot/Tools/HILSIM_XPlane$
```

**Comment by MatrixPilot** [comment]
For the first warning I think i've previously added a typecast in one of my
other PR's, so pretty simple fix there.

As for the second one, I already tried to fix it however it involves more
than a simple one liner - and hence I left it for the moment with
intentions to address the issue in a dedicated PR.

Right now i'm thinking we don't merge my current outstanding PR's, but
rather wait until i get everything better sorted out. I've found quite a
few issues i'm not completely happy with.

It's good to have you doing reviews though. Thanks.

**Comment by MatrixPilot** [comment]
Yes I had that problem too. It would be ideal to somehow detect the issue
and instruct our users on how to proceed, but it is pretty easy to find the
fix with a gsearch. As you're probably already aware, it's a result of
building a 32-bit target on a 64-bit platform.

**Comment by phollands** [comment]
Actually, I was not aware that it was a 32 bit build issue on a 64 bit platform. Thanks for that. In the past, I needed to use 32bit to get the build to work on my Imac.

I would really like also to get the Macos build, included in the main Makefile. I see on the Internet, that there are some good ways to establish the various platforms at the start of the Makefile, and I will try that out, and let you know how I get on.

Best wishes, Pete

**Comment by phollands** [comment]
Hi Robert,

Please can you use "Rebase" rather than "Merge", in the future, when bringing your branches up to date with master. Rebase will put all your changes on the end of history of commits from master.  Using Rebase ensures that the history of commits is linear, and easier to understand.

On a separate, point, I believe that the build of the HILSIM plugin, now disables the plugin by default, when X-Plane is first started. This confused me at first, when testing this branch. Is there a particular reason for disabling the plugin ? I had to re-enable the plugin after starting X-Plane, using the X-Plane plugin menu.

Best wishes, Pete

**Comment by Inspirati** [comment]
Shall-do with the rebase - hope I don't make a mess of it.

I noted that with the plugin too, and not sure why. I thought it had
something to do with X-Plane itself. I'll have a look into it later.

**Comment by phollands** [comment]
Robert,  For now, just leave the existing merge. I don't want you to lose this work. If necessary, let's merge the next change from master if required. However, getting "rebase" and "interactive rebase" working for you is  important as it  will give you much greater freedom with Git to change, sort commits, as well as Squash relevant commits together. 
Best wishes, Pete

**Comment by Inspirati** [comment]
I reviewed the documentation of squash the other day and I was planning to
run that before suggesting accepting the PR. I've never lost any work with
my previous rebase disasters, it's just that i've made such a mess of my
repository that I end up wiping it away and starting with a fresh fork.
Takes up a bit of time though..

**Pull request closed without merging**
