### PR TITLE
Travis update

### PR DESCRIPTION
**Pull request by Inspirati**
update the travis build system and quiet the SILSIM build warnings

### CODE REVIEW

**Comment by phollands** [comment]
Hi robert,

Thanks for updating the Travis build system. I really appreciate the time you have put into making that work, and having the version 1.26 compiler working will be super.

We  need to simplify this Pull Request from the current 179 commits, so that it is much easier to understand. 

 I am going to clone your branch, and have a look to see what I can do, and then I'll get back to you, on how the commits could be simplified.

Thanks again for this submission.

Best wishes, Pete

**Comment by Inspirati** [comment]
G'day Peter, I'm fighting with git rebase right now )-:

**Comment by phollands** [comment]
Robert, 

There are Two potential Tools:-

1) Interactive Rebase
2) Create Patch files, and apply to new specific branches, with separate pull requests. e.g. One branch that is the complete travis build patch applied to a new branch, and then a Pull Request created from the new branch.

Source Tree allows me to create a patch file from a selection of commits in the history of a branch. So it's easy to pick out all those commits that are for one feature e.g. Travis update.

Best wishes, Pete

**Comment by chiloschista** [comment]
Sorry for the offtopics, but I always feel more relaxed when I read that top coders here have intense relations with git too = : D
Ric

Inviato da TypeApp



Il giorno 8 Ott 2016, 10:57, alle ore 10:57, Pete Hollands <notifications@github.com> ha scritto:

**Comment by Inspirati** [comment]
I pretty much did what you suggest at option (2) above. However when I
created a new branch from my local master, it also of course has all the
commit history from my master. So back to square one with struggling with
the interactive rebase. Unfortunately I now feel like I've made such a mess
of the whole thing, I'll probably be going back to all to oft solution of
'starting again'...

I have nothing good to say about git!

**Comment by phollands** [comment]
Hi Robert,

I have cloned your MatrixPilot repository, and then looked for the branch that you are using for this pull request, but could not find it. I then re-looked at this Pull Request (PR) and see that you used an "unknown repository" for this PR.
unknown_repository
That is unusual, and will not work with our workflow. 

Can you tell me the location at which I will find the branch that you are using ?

Best wishes, Pete

**Comment by phollands** [comment]
Robert, I see now that you deleted the branch you had used. And you have created a new pull request #72 . Best wishes, Pete

**Comment by Inspirati** [comment]
yeah, i made a right mess out of that )-:

okay, so here's where i'm now at, and whilst i believe i've cleaned things
up somewhat, i'm still somewhat confused, and hopefully can get some help
in avoiding such a mess recurring..

1/ deleted my fork at Inspirati/MatrixPilot
2/ created a fresh fork of MatrixPilot/MatixPilot at Inspirati/MatrixPilot
3/ cloned Inspirati/MatrixPilot to local
4/ created a new local branch Inspirati/MatrixPilot::travis_update
5/ used 'meld' to manually merge my current work from a local backup
6/ git add .
7/ git commit -m "update travis build and quiet SILSIM compile warnings"
8/ git push --set-upstream origin travis-update
9/ posted pull request (PR)

now the new odd thing is when i use meld to compare
Inspirati/MatrixPilot::travis_update with MatrixPilot/MatrixPilot -- i see
no differences!!!

(and no, i'd not updated my local MatrixPilot/MatrixPilot with the current
version which i see you've just now accepted the PR on)

**Comment by phollands** [comment]
Hi Robert,

I have already a reviewed and approved your pull request and it is now in
master. That is probably why you see no differences between your branch in
your repository in your and master in the MatrixPilot repository.

Best wishes, Pete

**Comment by phollands** [comment]
Just to be clear, I have reviewed and merged Pull Request 72 (this one is 71). I suppose that you probably used the same branch branch name, travid_update, in pull request 72. It is best to always have one unique branch name for each Pull request. Having said that, it is normal to delete a branch from your own github repo after it has been merged to master, so it is possible to use the branch name again later.

**Comment by Inspirati** [comment]
okay, cool. lets for the moment go with that my reuse of the branch label
has led to my rather confusing observation.

now that my 'travis_update' PR is in master, my understanding is that i
delete my local copy of the branch, and push this up to Inspirati/
MatrixPilot? (i'll get onto this later)

then what i believe i need to do is sync my fork with MatrixPilot/
MatrixPilot, in order to get my own changes into my forks master.

so, working on my local copy of Inspirati/MatrixPilot, i run:

1/ git remote add upstream git@github.com:MatrixPilot/MatrixPilot.git

2/ git remote -v
origin    git@github.com:Inspirati/MatrixPilot.git (fetch)
origin    git@github.com:Inspirati/MatrixPilot.git (push)
upstream    git@github.com:MatrixPilot/MatrixPilot.git (fetch)
upstream    git@github.com:MatrixPilot/MatrixPilot.git (push)

3/ git fetch upstream
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From github.com:MatrixPilot/MatrixPilot
 * [new branch]      MatrixPilotCameraChase -> upstream/
MatrixPilotCameraChase
 * [new branch]      MatrixPilotMulti -> upstream/MatrixPilotMulti
 * [new branch]      MatrixPilot_3_x -> upstream/MatrixPilot_3_x
 * [new branch]      MatrixPilot_4_0_balloon_launch -> upstream/MatrixPilot
_4_0_balloon_launch
 * [new branch]      MatrixPilot_4_1 -> upstream/MatrixPilot_4_1
 * [new branch]      MatrixPilot_4_x -> upstream/MatrixPilot_4_x
 * [new branch]      MatrixPilot_AUAV2 -> upstream/MatrixPilot_AUAV2
 * [new branch]      MatrixPilot_AUAV3 -> upstream/MatrixPilot_AUAV3
 * [new branch]      MatrixPilot_AUAV3_fixes -> upstream/MatrixPilot
_AUAV3_fixes
 * [new branch]      MatrixPilot_AccelerationCompensation -> upstream/
MatrixPilot_AccelerationCompensation
 * [new branch]      MatrixPilot_CAN -> upstream/MatrixPilot_CAN
 * [new branch]      MatrixPilot_DB_Breeze -> upstream/MatrixPilot_DB_Breeze
 * [new branch]      MatrixPilot_FreeRTOS -> upstream/MatrixPilot_FreeRTOS
 * [new branch]      MatrixPilot_IP -> upstream/MatrixPilot_IP
 * [new branch]      MatrixPilot_NASA_challenge -> upstream/MatrixPilot
_NASA_challenge
 * [new branch]      MatrixPilot_OS -> upstream/MatrixPilot_OS
 * [new branch]      MatrixPilot_beta -> upstream/MatrixPilot_beta
 * [new branch]      MatrixPilot_fbw -> upstream/MatrixPilot_fbw
 * [new branch]      MatrixPilot_heli -> upstream/MatrixPilot_heli
 * [new branch]      MatrixPilot_helicalTurns -> upstream/MatrixPilot_
helicalTurns
 * [new branch]      MatrixPilot_helicalTurns_BalloonLaunch -> upstream/
MatrixPilot_helicalTurns_BalloonLaunch
 * [new branch]      MatrixPilot_legacy -> upstream/MatrixPilot_legacy
 * [new branch]      MatrixPilot_mw4 -> upstream/MatrixPilot_mw4
 * [new branch]      MatrixPilot_mw4fbw -> upstream/MatrixPilot_mw4fbw
 * [new branch]      MatrixPilot_nucleo -> upstream/MatrixPilot_nucleo
 * [new branch]      MatrixPilot_sonar -> upstream/MatrixPilot_sonar
 * [new branch]      MatrixPilot_vtol -> upstream/MatrixPilot_vtol
 * [new branch]      MatrixPilot_wjp_helicalTurns -> upstream/MatrixPilot_
wjp_helicalTurns
 * [new branch]      Matrixpilot_on_Madre_board -> upstream/Matrixpilot_on_
Madre_board
 * [new branch]      master     -> upstream/master
 * [new branch]      quad_testing -> upstream/quad_testing

now that seems a little verbose, and indeed confusing! - for why did my
local not already contain all these historical branches in the first place?
(anyhow, no matter, so long as this doesn't indicate i've previously gone
astray)

4/ git checkout master

5/ git merge upstream/master
Updating ac2df46..3dffe61
Fast-forward
 .travis.yml                       |  68
+++++++++++++++++++-------------------------------
 MatrixPilot/config.c              |   3 ++-
 MatrixPilot/helicalTurnCntrl.c    |   1 +
 Tools/MatrixPilot-SIL/SIL-udb.c   |   2 +-
 Tools/makefiles/toolchain-XC16.mk |   4 +--
 libDCM/estAltitude.h              |   8 +++---
 libUDB/heartbeat.h                |   6 ++---
 libUDB/libUDB.h                   |   2 +-
 makefile                          |   2 +-
 travis-install-dependencies.sh    | 123
++++++++++++++++++++++++++++++++++++++++--------------------------------------------------
 10 files changed, 95 insertions(+), 124 deletions(-)

6/ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean

7/ git push
Counting objects: 1, done.
Writing objects: 100% (1/1), 303 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To git@github.com:Inspirati/MatrixPilot.git
   ac2df46..3dffe61  master -> master

8/ git pull
Already up-to-date.

now i notice in the travis build output one outstanding warning:
../../libDCM/gpsParseUBX.c:628:7: warning: format ‘%i’ expects argument of
type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat]

so i run:

9/ git -b quickfix_warning

and i make a quick edit to 'gpsParseUBX.c' fix to address the warning

10/ git status
On branch quickfix_warning
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   libDCM/gpsParseUBX.c

no changes added to commit (use "git add" and/or "git commit -a")

11/ git add .

12/ git commit -m "quickfix of outstanding compiler warning on SILSIM build"

13/ git push --set-upstream origin quickfix_warning

then i create a new PR and review the travis output - looks like the
warning has been addressed (-:


So, is the moral of the story that with git, thou shall never make local
changes to ones own local master - as i suspect that's where i may have
been going astray?

**Comment by phollands** [comment]
Robert,

That workflow all looks pretty good to me. I don't use the git command lines, most of the time, so I'm not quite so familiar with them.

Yes, you do need to keep your local master up to date from upstream, and you need to keep it pristine and never change it yourself. The reason is that you will want to make branches, that are up to date with the main master on MatrixPilot/MatrixPilot master. But you cannot branch from a remote repository, you have to branch from a branch (which includes master) from your local repo. So your own master has to be pristine.

Pushing your local master to your origin master is probably optional just keeps your own github repository pristine as well. But in fact, it does not really matter that much to the workflow. Because you will create a local branch e.g. travis_update on your PC, and then when it is ready, push that to your origin (your own repo). It is that branch on your repo, which is then compared to MatrixPilot/MatrixPilot master when you do the pull request.

I am so glad that the work flow is starting to work for you.

I have rebased my mavlink_core_update branch onto your commits to master from your last two approved pull requests for the real travis update. That means travis is re-running it's tests with the latest changes against my pull request. That is all looking [really neat and tidy on the Travis Log.](https://travis-ci.org/MatrixPilot/MatrixPilot/builds/166030298)

Nice work.

Pete

**Comment by Inspirati** [comment]
okay, thanks for your feedback, and now onto the more troublesome spots (-;

aka, backup time!

**Pull request closed without merging**
