### PR TITLE
Move SILcat to own directory and add to scripted build targets. Move …

### PR DESCRIPTION
**Pull request by Inspirati**
…UDBSocket* to common location for all three targets which include them, adjusting the build system to suit.

### CODE REVIEW

**Comment by phollands** [comment]
Rob, I believe you are going to add some additional commits as this PR, as it currently stands, broke the build of the X-Plane HILSIM pluging (makefile.macos), and the build of SILSIM (makefile) on my Mac. The SILcat builds. Best wishes, Pete

**Comment by Inspirati** [comment]
yes, working on all of the above, and more..

**Comment by phollands** [comment]
Sounds super !

**Comment by Inspirati** [comment]
rebasing may be a problem, every other time i tried, i made a mess, and
hence i could really use your help with learning that.

git is both incredibly powerful, and awfully awful.. )-:

**Comment by Inspirati** [comment]
Hi Peter, trust you are doing well. I am away travelling for work at the
moment however have flagged this for my attention ASAP. Best wishes, Robert.

**Comment by phollands** [comment]
More than a year has past. So closing.

**Pull request closed without merging**
