### PR TITLE
Mp quad

### PR DESCRIPTION
**Pull request by Jeffem**

### CODE REVIEW

**Comment by phollands** [comment]
GFM, 

Thanks for offering this Pull Request (PR). It will require some careful testing as it is at the very heart of the system. There are two points that I have noticed right away:-

Where is GYRO_RANGE defined ? (Are we missing another file in this PR ?)

I note that until this PR, the libUDB directory (hardware boards directory) has deliberately had no knowledge of AIRFRAME_TYPE (e.g. AERO_QUAD), and so that test of if (AIRFRAME_TYPE == AIRFRAME_QUAD) will need to become something else that is board  / hardware related. 

Best wishes, Pete

**Comment by Jeffem** [comment]
Pete,

GYRO_RANGE was defined in ConfigUDB5.h, just after ACCEL_RANGE.

I will pull the new file.

AIRFRAME_TYPE=AIRFRAME_QUAD is currently a possible choice available in the main options.h file.

I will use intensively of this parameter in many files!

I have try to pull MPU6000.c on the github in my MP_Quad branch to test the github mechanism.

I am not yet familiar with github, especially what stay private and what is visible for the community.

 

Introducing the Quadcopter in MP has many consequences in many files and the complete version need to have all the files to gather before compilation.

I have tried to separate different improvement (Lidar, Baro, Multicopter,…)  in an “autoporteuse” manner but the options.h file is modified each time.

I have a current version of the document written to explain my work. I can send you it to have a global view, if you wish.

Give me how I can do, in a confidential way.

 

Best wishes, gfm

 

De : Pete Hollands [mailto:notifications@github.com] 
Envoyé : mercredi 23 novembre 2016 18:10
À : MatrixPilot/MatrixPilot
Cc : Jeffem; Author
Objet : Re: [MatrixPilot/MatrixPilot] Mp quad (#101)

 

GFM,

Thanks for offering this Pull Request (PR). It will require some careful testing as it is at the very heart of the system. There are two points that I have noticed right away:-

Where is GYRO_RANGE defined ? (Are we missing another file in this PR ?)

I note that until this PR, the libUDB directory (hardware boards directory) has deliberately had no knowledge of AIRFRAME_TYPE (e.g. AERO_QUAD), and so that test of if (AIRFRAME_TYPE == AIRFRAME_QUAD) will need to become something else that is board / hardware related.

Best wishes, Pete

**Comment by phollands** [comment]
GFM,  your pull request is for these changes to go into master. If you look at the master branch, there is no GYRO_RANGE parameter in ConfigUDB5.h . So you need to include that new line for GYRO_RANGE  in your Pull Request. You need to add a commit of the changes in ConfigUDB5.h to your branch.  If you are in doubt about the git / github work flow, then please watch my two videos. 1st video  [is here.](https://vimeo.com/163824531) Best wishes, Pete

**Comment by Inspirati** [comment]
I note the entire functionality of mpu6000.c is preprocessed out for the UDB4 board, and hence the existing check within its code is rather redundant!

**Comment by Inspirati** [comment]
Keeping AIRFRAME_TYPE out of libUDB is quite desirable, and in my 'bigger picture' vision of separating out the various layers the likes of this option would not even be visible at the lowest level. aka, my desire to break options.h into smaller chunks, so that only relevant options get included at the various layers.

For years now i've been aiming to achieve just this, however it will take a lot of high risk chances which could easily introduce compile issues to other targets. That said, I do believe this goal is worth aiming for - not only because it'll make porting to new targets that much simpler in the long run..

Jeffem, please copy me with your document, for i'm keen to see what you've got in mind (-:

**Comment by Inspirati** [comment]
I'd like to suggest making the mpu6000 sample rate a runtime option specified via the initialisation routine:

void MPU6000_init16(callback_fptr_t fptr);

By adding another parameter to this function:

void MPU6000_init16(callback_fptr_t fptr, int sample_rate);

The option can be specified from the upper layer.

**Comment by Inspirati** [comment]
And while your at it, if you could consider renaming MPU6000_init16 to mpu6000_init, along with the couple of other external prototypes being changed from 'MPU' to 'mpu', will help move towards a naming convention i'd like to see, where-by all exposed function names are prefixed exactly the same as the entire module name - in this case mpu6000. Trivial yes, but consistency can go a long way towards improving overall readability.

In this case it's next to trivial, as the only other guilty functions appear to be:

static void MPU6000_read(void)
void MPU6000_print(void)

The former being static and therefore a non-issue, and a quick ack-grep on the latter reveals it's not actually called from anywhere in the codebase.

BTW: the '_init16' is massively legacy, from the very first days of MarkW's work in developing the driver for the mpu6000. We no longer have any semblance of an eight bit mode configuration of the device.

**Comment by Jeffem** [comment]
Hi Robert,

I am pleased to send you the current draft version of my document about Quadcopter implementation in MatrixPilot.

I used MP_4.1 as reference, all flights are done in this context.

I am currently working on migrate the gfm_modifications in the new MP5 release code, using github, but I still have some difficulties with github mechanisms.

When I worked on the in flight data, I discovered too much noise in the motors commands.

The Quad flies pretty well, but I am worry about LiPo autonomy and ESC illness.

So I stop the software development to work on reducing noise sources on board.

I have made a vibration tool with a MPU6050 connected to Microchip development board to acquire and transfer on the PC data at high rate.

 

Please, feel free to make any comment or suggestion about that document.

And excuse my EnglishJ

Best regards, gfm

 

De : Robert Dickenson [mailto:notifications@github.com] 
Envoyé : jeudi 24 novembre 2016 11:28
À : MatrixPilot/MatrixPilot
Cc : Jeffem; Author
Objet : Re: [MatrixPilot/MatrixPilot] Mp quad (#101)

 

Keeping AIRFRAME_TYPE out of libUDB is quite desirable, and in my 'bigger picture' vision of separating out the various layers the likes of this option would not even be visible at the lowest level. aka, my desire to break options.h into smaller chunks, so that only relevant options get included at the various layers.

For years now i've been aiming to achieve just this, however it will take a lot of high risk chances which could easily introduce compile issues to other targets. That said, I do believe this goal is worth aiming for - not only because it'll make porting to new targets that much simpler in the long run..

Jeffem, please copy me with your document, for i'm keen to see what you've got in mind (-:

**Comment by phollands** [comment]
GFM,  please could you also send me your draft document about implementing Quadcopter in MatrixPilot. Thanks Pete

**Comment by Jeffem** [comment]
Hi Pete, with pleasure !

I am not yet familiar with this corresponding link via github : when I answer to this email, does this email and its join doc are visible by every body in the world, only our community or yourself only?

Because, as you will see, this document is not complete and is comprehensive only by gentlenav guys knowing MP!

Best regards,

gfm 

 

De : Pete Hollands [mailto:notifications@github.com] 
Envoyé : vendredi 25 novembre 2016 11:22
À : MatrixPilot/MatrixPilot
Cc : Jeffem; Author
Objet : Re: [MatrixPilot/MatrixPilot] Mp quad (#101)

 

GFM, please could you also send me your draft document about implementing Quadcopter in MatrixPilot. Thanks Pete

**Comment by phollands** [comment]
Guy Francois, Thanks for trying to send your change about improving rmat.c .  I will write to you offline about this Pull Request, as you will need to present your Pull Requests in a different way completely, and you should not use the File Upload facility, for requesting a small change of a few lines. So I will close this Pull Request now, and we can have another go together, once we've discussed git and github a little more. Best wishes, Pete

**Pull request closed without merging**
