### PR TITLE
Interrupt priority analysis

### PR DESCRIPTION
**Pull request by phollands**
For many years, I've wanted to be able to see the millisecond level interaction of the various interrupt routines in MatrixPilot. This block of code has let me view the interactions between interrupts in much greater detail.  I enclose  example screenshots below using the Salae Logic Analyser.

The first screenshot shows a 1 second overview. The GPS data is arriving at 4HZ (HILSIM UDB4). 
screen shot 2017-01-12 at 13 15 38

In the second screenshot, a close up on the arrival of the 1st GPS block of data,  you can see the GPS navigation thread being interrupted by the DCM thread, so that the GPS thread does not complete until after the DCM thread has completed.

screen shot 2017-01-12 at 13 14 21

I am going to test this code in more detail before merging (especially for the AUAV3), but I would like to leave the code here in this pull request for a few days, to give the team time to make any constructive comments, before I complete final testing (and flight test of the code without this running).

Best wishes, Pete

### CODE REVIEW

**Comment by phollands** [comment]
Although Travis has passed the code, the actual code does not build in MPLAB-X after running "bash proj_gen.sh", and the related commit above.

Robert, I wonder if you have any suggestions about the following ?

The "Library" folder in MPLAB-X is now empty...
screen shot 2017-02-08 at 17 04 08

And the error on compiling looks like this ...
screen shot 2017-02-08 at 17 03 21

I note that proj_gen.sh has not been run for a while, and that quite a few other alterations were made as I ran the generator, besides including the new file servoOutPins.h . (see commit above).

**Comment by phollands** [comment]
Correction: I said the Library folders is now empty. I should have said the Microchip folder is now empty.

**Comment by KeesGuijt** [comment]
Pete, Robert,

I've had similar problems last november. I changed Tools\makefiles\target-MatrixPilot.mk in my branch:

# this file is included from makefile

#ifeq ($(DEVICE),PX4)
#modules := MatrixPilot MAVLink libDCM
#incpath := MAVLink/include
#else
#modules := MatrixPilot MAVLink libDCM libVectorMatrix
modules := MatrixPilot MAVLink libDCM libVectorMatrix libFlashFS Microchip
incpath := MAVLink/include Microchip Microchip/Include libVectorMatrix
#defines := NOFS
#defines :=
#endif
cfgpath := Config

Hope this helps.
Kees

**Comment by phollands** [comment]
I've regenerated the MPLAB-X configuration files following on from the fix to proj-gen.sh in PR #123 , so this compiles correctly now within the MPLAB-X IDE.

**Comment by phollands** [comment]
I have tested this branch on all three autopilot stacks (UDB4, UDB5, and AUAV3) and it is working correctly.

**Pull request merged**
