### PR TITLE
Test osd gps num flash for low svs

### PR DESCRIPTION
**Pull request by elgarbe**
This PR is for solve [issue #94 ](https://github.com/MatrixPilot/MatrixPilot/issues/94)
Here a [video with the new feature](https://www.youtube.com/watch?v=F8ZsV9PYIB0)

### CODE REVIEW

**Comment by phollands** [comment]
Hi Leo,  

Thanks very much for this feature. I have just two comments for now.

1) For merging this into Master, we will need the options for using the OSD turned [off in this commit, ](https://github.com/MatrixPilot/MatrixPilot/pull/95/commits/93ca09afa0adf51b385e899d74834a1cd3ed2636)the legacy pinout options also turned off.
2) Could you Squash these 9 commits into one commit using SourceTree ? That will involve you using the option for  an "Interactive Rebase". If you have problems with squashing the 9 commits into one commit, then I can do it when I approve the Pull Request, but I thought you might like to give that a go as it is a useful git / sourcetree feature. :-)

Best wishes, Pete

**Comment by phollands** [comment]
The link to the video did no work.

**Comment by phollands** [comment]
OK, I found [the video.](https://www.youtube.com/watch?v=F8ZsV9PYIB0)

**Comment by Inspirati** [comment]
Since this is a valuable feature with very little additional overhead I'd suggest doing away with the conditional compilation. Conditional compilation paths are ugly, take a lot of extra maintenance in the test code to cover both options, and hence I'd rather see them reduced where-ever possible (-:

**Comment by elgarbe** [comment]
Ok, so, I will remove OSD_NUM_SATS_FLASH_LOW_SVS define and conditional compilation around it. Right?
Then I will squash all the commit into jus one (I will search for some guide and will ask before proced).
Thank

**Pull request closed without merging**
